'''
Created on Sep 18, 2013

@author: kirill lykov
'''
from itertools import dropwhile
from collections import OrderedDict

class Atom2objTranslator:
    
    def is_not_atom_section(self, s):
        return (s.rstrip() != "Atoms")
    
    def is_not_angle_section(self, s):
        return (s.rstrip() != "Angles")
    
    def getAtomIndex(self, s):
        words = s.split()
        return int(words[0])
    
    def atom2vertex(self, s):
        words = s.split()
        res = ' '.join(['v', words[3], words[4], words[5]])
        return res
    
    def angle2face(self, s, old2new):
        words = s.split()
        v = []
        for i in range(2, 5):
            v.insert( i - 1, str(old2new[int(words[i])]) )
        res = ' '.join(['f', v[0], v[1], v[2]])
        return res
    
    def checkAngle(self, vertices, line):
        words = line.split()
        for i in range(2, 5):
            v = int(words[i])
            if (v not in vertices):
                return False
        return True
    
    def angleToVertices(self, line):
        words = line.split()
        res = list()
        for i in range(2, 5):
            v = int(words[i])
            res.append(v)
        return res
    
    # get sorted lines from file according to the fist number (required by obj format)
    def getSortedAtomsLines(self, lines):
        atomsDict = {}
        alreadyParsed = False
       
        for line in lines:
            line = line.rstrip()
            line = line.rstrip()
            # skip Atoms and the first line after Atoms section
            if (line == "Atoms"): continue
            if ((not line) and (not alreadyParsed)):
                alreadyParsed = True
                continue
            # break when came to the end of the section
            if (not line) and (alreadyParsed):
                break
            words = line.split()
            assert(len(words) > 0)
            n = int(words[0])
            atomsDict[n] = line;
        
        return OrderedDict(sorted(atomsDict.items(), key=lambda t: t[0]))
    
    def run(self, inputFileName, outputFileName):
        try:
            verticesFromAngles = set() # to avoid adding point which has no angles
            with open(inputFileName, 'r') as f:
                # parse Angles
                alreadyParsed = False    
                lines = dropwhile(self.is_not_angle_section, f)
                for line in lines:
                    line = line.rstrip()
                    # skip Atoms and the first line after Angles section
                    if (line == "Angles"): continue
                    if ((not line) and (not alreadyParsed)):
                        alreadyParsed = True
                        continue
                    # break when came to the end of the section
                    if (not line) and (alreadyParsed):
                        break
                    
                    verticesFromAngles.update(self.angleToVertices(line))
            
            output = open(outputFileName, "w")
            output.write("# Generated by atom2obj script\n\n")
            
            with open(inputFileName, 'r') as f:
                
                # set of vertices to check that all vertices mentioned in Angles are in Atoms
                vertices = set()
                
                lines = dropwhile(self.is_not_atom_section, f)
                
                atomsDict = self.getSortedAtomsLines(lines)
                old2new = dict()
                # parse Atoms and write
                output.write("\n# Vertex list\n\n")
                newLineInd = 1
                for ind in atomsDict:
                    line = atomsDict[ind]
                    
                    vertices.add(self.getAtomIndex(line))
                    old2new[self.getAtomIndex(line)] = newLineInd
                    outLine = self.atom2vertex(line)
                    if ind in verticesFromAngles:
                        output.write(outLine + "\n")
                    newLineInd = newLineInd + 1
                
                # parse Angles
                output.write("\n# Triangle list\n\n")
                alreadyParsed = False    
                lines = dropwhile(self.is_not_angle_section, lines)
                for line in lines:
                    line = line.rstrip()
                    # skip Atoms and the first line after Angles section
                    if (line == "Angles"): continue
                    if ((not line) and (not alreadyParsed)):
                        alreadyParsed = True
                        continue
                    # break when came to the end of the section
                    if (not line) and (alreadyParsed):
                        break
                    
                    if (not self.checkAngle(vertices, line)):
                        raise RuntimeError("There are vertices from Angles section which are not in Atoms section. Line content is \"" + line + "\"")
                    outLine = self.angle2face(line, old2new)
                    output.write(outLine + "\n")
                    
        except IOError:
            print("Error: can\'t find file or read data")
        except RuntimeError as e:
            print(e.args)
        finally:            
            f.close()
            output.close()
